### ISSUE TITLE
OneContext not initiated! please use builder method

### ISSUE THREAD

**Issue by babulpatel1309** [emanuel-braz/one_context#3]
Hi, I loved your package and especially it solved the basic problem of passing build context everywhere. So basically I wanted to show the snackbar very easily but couldn't able to, due to flutters limitations. Well I've used your package and I must say I'm very much happy with but I'm getting one error on the start of the application which is this:

`E/flutter ( 7896): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: 'package:one_context/src/controllers/one_context.dart': Failed assertion: line 17 pos 9: '_context != null': OneContext not initiated! please use builder method.
E/flutter ( 7896): 
E/flutter ( 7896): You need to use the OneContext().builder function to be able to show dialogs and overlays! e.g. ->
E/flutter ( 7896): 
E/flutter ( 7896):  MaterialApp(
E/flutter ( 7896):     builder: OneContext().builder,
E/flutter ( 7896):     ...
E/flutter ( 7896):  )
E/flutter ( 7896): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter ( 7896): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter ( 7896): #2      OneContext.context (package:one_context/src/controllers/one_context.dart:17:9)
E/flutter ( 7896): #3      OneThemeController.loadThemeMode (package:one_context/src/controllers/one_theme_controller.dart:80:50)
E/flutter ( 7896): <asynchronous suspension>
E/flutter ( 7896): #4      new OneThemeController (package:one_context/src/controllers/one_theme_controller.dart:26:5)
E/flutter ( 7896): #5      new OneContext._private (package:one_context/src/controllers/one_context.dart:49:16)
E/flutter ( 7896): #6      OneContext.instance (package:one_context/src/controllers/one_context.dart:52:43)
E/flutter ( 7896): #7      OneContext.instance (package:one_context/src/controllers/one_context.dart)
E/flutter ( 7896): #8      new OneContext (package:one_context/src/controllers/one_context.dart:53:27)
E/flutter ( 7896): #9      WlcmClubApp.navKey (package:wlcmclub/app.dart:33:7)
E/flutter ( 7896): #10     WlcmClubApp.navKey (package:wlcmclub/app.dart)
E/flutter ( 7896): #11     _WlcmClubAppState.build (package:wlcmclub/app.dart:72:37)
E/flutter ( 7896): #12     StatefulElement.build (package:flutter/src/widgets/framework.dart:4663:28)
E/flutter ( 7896): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4546:15)
E/flutter ( 7896): #14     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
E/flutter ( 7896): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
E/flutter ( 7896): #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
E/flutter ( 7896): #17     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4710:11)
E/flutter ( 7896): #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
E/flutter ( 7896): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter ( 7896): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
E/flutter ( 7896): #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
E/flutter ( 7896): #22     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
E/flutter ( 7896): #23     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
E/flutter ( 7896): #24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
E/flutter ( 7896): #25     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4710:11)
E/flutter ( 7896): #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
E/flutter ( 7896): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter ( 7896): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
E/flutter ( 7896): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
E/flutter ( 7896): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
E/flutter ( 7896): #31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
E/flutter ( 7896): #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
E/flutter ( 7896): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter ( 7896): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:3255:20)
E/flutter ( 7896): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
E/flutter ( 7896): #36     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
E/flutter ( 7896): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
E/flutter ( 7896): #38     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:33)
E/flutter ( 7896): #39     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:866:20)
E/flutter ( 7896): #40     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
E/flutter ( 7896): #41     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
E/flutter ( 7896): #42     SchedulerBinding.handleDrawFrame (package:flutter/src/schedule`

Can you please help me to sort this thing.

### Here is my configuration

`static final GlobalKey<NavigatorState> navKey =  OneContext().key;`

and in the material app code:

` navigatorKey: WlcmClubApp.navKey,
  builder: OneContext().builder,`

**Comment by emanuel-braz** [comment]
Hi @babulpatel1309 thank you for the feedback! 

I think you are facing the same issue #2 . Basically you can't call showSnackBar before the first build of MaterialApp, cause the context used by the lib to show dialogs, needs to loaded under MaterialApp context.

Please try to verify if there is a call of OneContext method before the MaterialApp build and/or try to verify if the OneContext already has loaded the context, in this way:

```dart
if (OneContext.hasContext) {
    OneContext().showSnackBar (...);
}
```

Can you check that?

**Comment by babulpatel1309** [comment]
hey @emanuel-braz i've tried with the above solution, and also debugged the code whether app is calling any function of onecontext before initialization. But my application is not doing anything before initialization. So may be its because something is happening at the time of initialization.

**Comment by emanuel-braz** [comment]
Can you provide a sample project reproducing this behavior? So I can investigate more deeply

**Comment by emanuel-braz** [comment]
I'm closing this issue because of inactivity
